name: Hello World Docker Action
description: This action tells the world, "Hello"
inputs:
  who-to-greet:
    description: Who to greet
    required: true
    default: World

outputs:
  time:
    description: "When this script was ran"

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.who-to-greet }}
