name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [ .github/** ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * SUN'
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
    

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The name of the event that triggered this workflow was ${{ github.event_name }}"
          echo "The ref is ${{ github.ref }}, while the repo is ${{ github.repository }}"
      - uses: actions/checkout@v4
      - run: tree
  Test:
    runs-on: ubuntu-latest
    needs: Build
    environment: Test
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - run: echo "Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    needs: Build
    environment: Load-Test
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - run: |
          echo "Testing..."
          sleep 15

  Prod:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment:
      name: Production
      url: https://writeabout.net
    if: ${{ github.event.inputs.environment == 'Production' }}
    steps:
      - run: echo 'Step 1 deploying...'
      - run: sleep 10      
      - run: echo 'Step 2 deploying...'
      - run: sleep 10
      - run: echo 'Step 3 deploying...'
      - run: sleep 10
      - run: echo 'Step 4 deploying...'
      - run: sleep 10
      - run: echo 'Step 5 deploying...'
      - run: sleep 10
