name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [ .github/** ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * SUN'
  workflow_dispatch:
    

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The name of the event that triggered this workflow was ${{ github.event_name }}"
          echo "The ref is ${{ github.ref }}, while the repo is ${{ github.repository }}"
      - uses: actions/checkout@v4.0
      - run: tree
