name: HW Docker CI

on:
  push:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - id: hello-world
        uses: ./hello-world-docker-action
        with:
          who-to-greet: "Y'all"

      - run: echo "This workflow was run at ${{ steps.hello-world.outputs.time }}
